[project]
name = "fractal-generator"
version = "0.1.1"
requires-python = ">=3.13"
dependencies = [
    "matplotlib==3.10.1",
    "loguru==0.7.3",
    "opencv-python==4.11.0.86"
]

[tool.ruff]
select = ["ALL"]
